/* =========================================================
   pol-ua 500 — exam #2 data
   CARDS (30) · ESSAYS (10)
   ========================================================= */

const CARDS = [
  { term:"Spatial / Sincere Voting", cat:"Voting & Participation", def:"Voting for the candidate closest to your own policy preferences, with no strategic calculation.", hint:"Pure preference expression — no gaming the system." },
  { term:"Median Voter Theorem", cat:"Voting & Participation", def:"In a two-candidate race with single-peaked preferences, the winning candidate is closest to the median voter's position.", hint:"Both parties converge to the center — explains why platforms often look alike." },
  { term:"Strategic Voting", cat:"Voting & Participation", def:"Voting for a less-preferred candidate to prevent a worse outcome (e.g., voting for your 2nd choice to block your last choice).", hint:"Common in FPTP systems — voting for the 'lesser evil'." },
  { term:"Vote Buying", cat:"Voting & Participation", def:"Exchanging material goods, money, or favors for votes; a form of electoral clientelism.", hint:"Undermines electoral integrity; studied via turnout anomalies." },
  { term:"Credible Exit Option", cat:"Voting & Participation", def:"The ability to genuinely leave a political relationship, giving citizens real leverage over the state.", hint:"Exit is credible only if leaving is actually feasible." },
  { term:"Voice (Hirschman)", cat:"Voting & Participation", def:"Using speech, protest, or political action to change an organization from within.", hint:"Voice is chosen when exit is too costly or loyalty is high." },
  { term:"Loyalty (Hirschman)", cat:"Voting & Participation", def:"Remaining in a relationship despite dissatisfaction, hoping things improve.", hint:"Loyalty suppresses both exit and voice." },
  { term:"Collective Action Problem", cat:"Voting & Participation", def:"Individually rational behavior (free-riding) leads to a collectively suboptimal outcome — e.g., no one votes because each vote seems not to matter.", hint:"Core reason voter turnout is 'puzzling' from a rational-choice view." },
  { term:"Selective Incentives", cat:"Voting & Participation", def:"Private benefits given only to those who participate, used to overcome the collective action problem.", hint:"Olson's solution: make participation individually worthwhile." },
  { term:"Public Good", cat:"Voting & Participation", def:"A non-excludable and non-rival benefit — everyone benefits regardless of contribution.", hint:"Public goods create free-rider problems → collective action dilemma." },
  { term:"Ethnicity (Chandra)", cat:"Ethnicity & Identity", def:"A subset of identity categories where membership is determined by descent-based attributes: ancestry, race, language, religion, tribe, caste, etc.", hint:"Key: descent-based, not freely chosen. Distinct from other social identities." },
  { term:"Ethnic Fractionalization", cat:"Ethnicity & Identity", def:"The probability that two randomly selected individuals belong to different ethnic groups. Higher = more diverse.", hint:"Does NOT capture inequality between groups — distinct from polarization." },
  { term:"Primordialism", cat:"Ethnicity & Identity", def:"View that ethnic identities are ancient, fixed, and emotionally deep-rooted — almost biological.", hint:"Criticized: ignores how identities shift historically." },
  { term:"Instrumentalism", cat:"Ethnicity & Identity", def:"View that ethnic identities are tools — elites manipulate them to mobilize voters and gain power.", hint:"Ethnicity as strategy, not essence." },
  { term:"Constructivism", cat:"Ethnicity & Identity", def:"View that ethnic identities are socially constructed and historically contingent — real but malleable.", hint:"Dominant modern view: identities are built, not given, but powerful once built." },
  { term:"Party Identification / Partisanship", cat:"Parties & Systems", def:"A psychological attachment or sense of belonging to a political party, often stable over time.", hint:"Distinct from 'which party you vote for' — it's identity." },
  { term:"Running Tally (Fiorina)", cat:"Parties & Systems", def:"Partisanship = a running average of past performance evaluations of each party. Retrospective and updateable.", hint:"Partisanship is rational — you update based on what parties actually do." },
  { term:"Social Identity (Partisanship)", cat:"Parties & Systems", def:"Green, Palmquist & Schickler view: partisanship is a social identity ('I am a Democrat') — stable, resistant to policy shifts, like team loyalty.", hint:"Explains why people don't switch parties even when their party underperforms." },
  { term:"Political Party", cat:"Parties & Systems", def:"An organization that competes in elections with the goal of placing its candidates in government office.", hint:"Distinguished from interest groups, which don't run candidates." },
  { term:"One-Party System", cat:"Parties & Systems", def:"Only one party is legally allowed to exist or compete; opposition is banned.", hint:"E.g., China (CCP), Soviet-era USSR." },
  { term:"Single-Party Dominant System", cat:"Parties & Systems", def:"Multiple parties exist and compete but one wins elections consistently over long periods.", hint:"E.g., Japan (LDP), South Africa (ANC), Sweden (Social Democrats historically)." },
  { term:"Two-Party System", cat:"Parties & Systems", def:"Two major parties dominate; third parties rarely win. Product of FPTP electoral rules + Duverger's Law.", hint:"E.g., USA, UK historically." },
  { term:"Multi-Party System", cat:"Parties & Systems", def:"Three or more parties regularly win seats and can govern. Common under proportional representation.", hint:"E.g., Germany, Netherlands, Israel." },
  { term:"Effective Number of Parties", cat:"Parties & Systems", def:"A weighted measure of how many parties really matter (by seat/vote share), not just how many exist.", hint:"Formula: 1 / Σ(seat share²). 10 tiny parties ≠ 10-party system." },
  { term:"Reinforcing Cleavages", cat:"Parties & Systems", def:"Multiple social divisions (class, religion, ethnicity) line up — the same people are on the same side on every issue.", hint:"Creates strong, stable, polarized parties — but more conflict." },
  { term:"Cross-Cutting Cleavages", cat:"Parties & Systems", def:"Social divisions cut across each other — a person may be working-class AND religiously conservative AND an ethnic minority.", hint:"Moderate political conflict; people have cross-pressured loyalties." },
  { term:"Duverger's Law", cat:"Parties & Systems", def:"FPTP systems tend to produce two-party systems; proportional representation tends to produce multi-party systems.", hint:"Mechanism: strategic voting + party entry decisions under FPTP squeeze out third parties." },
  { term:"Party System Institutionalization", cat:"Parties & Systems", def:"The degree to which a party system is stable, rooted in society, and follows predictable rules of competition.", hint:"Mainwaring & Scully: 4 dimensions — volatility, societal roots, legitimacy, organization." },
  { term:"Electoral Volatility", cat:"Parties & Systems", def:"The aggregate shift in vote shares between parties across elections. High volatility = unstable party system.", hint:"Pedersen Index = sum of absolute vote share changes ÷ 2." },
  { term:"Electoral Integrity", cat:"Parties & Systems", def:"The extent to which elections conform to international norms: free, fair, transparent, competitive, free from fraud/violence.", hint:"Measured via expert surveys, forensic stats, observed anomalies." },
];

const ESSAYS = [
  { q:"Under what conditions might a citizen use Voice vs. Exit vs. Loyalty?", hint:"Voice: when exit is costly, loyalty is moderate, voice feels effective.\nExit: when alternatives exist, cost of leaving is low, voice seems futile.\nLoyalty: when attachment is high, exit isn't feasible, hope remains.\nKey driver: credibility of the exit option." },
  { q:"What is the collective action dilemma? Why does it predict low individual participation?", hint:"Each individual's contribution is too small to matter alone → rational to free-ride.\nBut if everyone free-rides → collective good (political change) is not provided.\nSolution: selective incentives, social pressure, expressive benefits." },
  { q:"Why do people bother to vote at all?", hint:"1. Civic duty / expressive voting\n2. Social pressure / norms\n3. Selective incentives (party mobilization)\n4. Close elections raise perceived impact\n5. Low cost of voting (habits, proximity)\n6. Partisan identity drives turnout" },
  { q:"Why is SES often positively correlated with political participation?", hint:"Higher SES → more resources (time, money, civic skills), more political information, more policy stakes, more party mobilization." },
  { q:"Under what conditions might SES NOT be positively correlated with participation?", hint:"Authoritarian contexts: poor mobilized by clientelism or fear.\nStrong ethnic/communal mobilization: identity overrides class.\nExtreme grievance: high-intensity movements mobilize low-SES groups.\nInverse: wealthy exit (private solutions) rather than engage politically." },
  { q:"What does ethnic diversity suggest for democratic politics?", hint:"Not deterministic. Problems arise IF: reinforcing cleavages, ethnicity is politicized, weak institutions.\nLess damaging when: cross-cutting cleavages, constructivist fluidity, strong party systems.\nEthnic fractionalization alone doesn't predict democratic breakdown." },
  { q:"What evidence suggests partisanship is a social identity rather than a rational running tally?", hint:"Stability across dramatic party policy shifts.\nAffective polarization beyond policy disagreement.\nParty preference precedes policy views (not the reverse).\nIntermarriage preferences, social sorting by party." },
  { q:"Why do some countries have more parties than others?", hint:"1. Electoral system: PR → more parties (Duverger's Law)\n2. Social cleavages: more distinct groups → more parties\n3. Low legal thresholds\n4. Federalism: regional parties viable\n5. Historical path dependence" },
  { q:"How would you assess whether a country has high party system institutionalization?", hint:"1. Low electoral volatility (stable vote shares)\n2. Parties have roots in society (not just leader vehicles)\n3. Parties seen as legitimate actors\n4. Parties have strong internal organizations\n(Mainwaring & Scully's 4 dimensions)" },
  { q:"Why is electoral fraud difficult to measure?", hint:"It's hidden by definition. Methods: expert surveys (PEI), digit-based forensics (Benford's Law), turnout anomalies, precinct-level outliers, satellite imagery, observer reports.\nLimitation: forensic stats produce false positives; surveys are subjective." },
];
