/* =========================================================
   1Z0-1080-25 — Oracle Planning 2025 Implementation Professional
   CARDS (33) · ESSAYS (10) · ESSAY_MC (10) · EXAM_Q (8)
   Categories:
     "Application Setup"   — Planning overview, dims, metadata/data, security
     "Content & Rules"     — Forms/dashboards/navflows, rules, reports
     "Modules"             — Financials, Workforce, Capital, Projects, Strategic Modeling
     "Operations"          — Maintenance, IPM, Approvals
   ========================================================= */

const CARDS = [
  /* ---------------- Application Setup (8) ---------------- */
  { term:"Planning Application",
    cat:"Application Setup",
    def:"An Oracle Cloud EPM application built on Essbase cubes that supports budgeting, forecasting, and what-if analysis across standard business processes or Custom modules.",
    hint:"Created from Planning or FreeForm; stored in EPM Cloud." },
  { term:"FreeForm Application",
    cat:"Application Setup",
    def:"A flexible Planning application type that lets you define your own cubes and dimensions without enabling the pre-built modules (Financials, Workforce, etc.).",
    hint:"Pick this when you don't want the module content; you design dims yourself." },
  { term:"Required Dimension",
    cat:"Application Setup",
    def:"A dimension that every Planning application must contain: Account, Period, Year, Scenario, Version, and Entity (plus Currency when multicurrency is enabled).",
    hint:"Six required dims; Currency is added automatically when multicurrency is on." },
  { term:"User-Defined Dimension",
    cat:"Application Setup",
    def:"A custom dimension you add to model business-specific analysis (Product, Market, Department, etc.). Up to the Essbase cube's dimension limits.",
    hint:"Added after required dims; drives custom analysis in BSO/ASO cubes." },
  { term:"Dimension Hierarchy",
    cat:"Application Setup",
    def:"The parent-child tree structure of a dimension that controls aggregation. Base members hold data; upper-level members roll up via consolidation operators (+, -, ~, ^).",
    hint:"Tilde (~) = don't consolidate; caret (^) = never consolidate." },
  { term:"Valid Intersection",
    cat:"Application Setup",
    def:"A rule that restricts which cell combinations across dimensions can accept or display data, enforcing that only meaningful intersections are visible.",
    hint:"Example: Capex accounts only valid for Capital entities." },
  { term:"Cell-Level Security",
    cat:"Application Setup",
    def:"Security applied at specific dimension intersections to hide or restrict data, in addition to artifact-level access, using member combinations.",
    hint:"Finer-grained than Read/Write on a form — targets cells, not artifacts." },
  { term:"Data Map",
    cat:"Application Setup",
    def:"An EPM Cloud feature that pushes data from one cube or application to another by mapping source and target dimensions, including smart pushes from forms.",
    hint:"Used to move data between Plan Types or apps; supports Smart Push on save." },
  { term:"Data Integration",
    cat:"Application Setup",
    def:"The EPM Cloud tool (formerly Data Management) that imports/exports data with mapping rules, dimension mapping, drill-through, and scheduled jobs.",
    hint:"Replaces legacy Data Management; supports file, direct, and connected integrations." },

  /* ---------------- Application Setup cont. — Security (2) ---------------- */
  { term:"Security Provisioning",
    cat:"Application Setup",
    def:"Assigning predefined roles (Service Administrator, Power User, User, Viewer) to users or groups at the application level to control what features they can use.",
    hint:"Roles are hierarchical: Service Administrator > Power User > User > Viewer." },
  { term:"Access Permissions",
    cat:"Application Setup",
    def:"Read / Write / None / Deny permissions assigned to members, forms, rules, and other artifacts, granted to users or groups and evaluated with None overriding Write.",
    hint:"Union of group rights, but Deny (None) always wins over Write." },

  /* ---------------- Content & Rules (8) ---------------- */
  { term:"Data Form",
    cat:"Content & Rules",
    def:"A grid-based input and analysis surface where planners enter, view, and analyze data. Point-of-view and page dimensions define context; rows/columns show members.",
    hint:"Simple forms = single layout; composite forms embed multiple forms together." },
  { term:"Composite Form",
    cat:"Content & Rules",
    def:"A form that combines multiple simple forms into one layout so users can see and update related data side-by-side with shared POVs where applicable.",
    hint:"Useful for master-detail entry; saves navigation between forms." },
  { term:"Dashboard",
    cat:"Content & Rules",
    def:"A visual layout that combines charts, grids, forms, and commentary to summarize planning data. Supports drill-down, interactive filters, and global POVs.",
    hint:"Dashboard 2.0 is the modern engine with richer charts and layout control." },
  { term:"Navigation Flow",
    cat:"Content & Rules",
    def:"A configurable UI path with cluster cards, tabs, and sub-tabs that customizes the user experience per role or group, hiding artifacts not relevant to them.",
    hint:"Role-scoped flows simplify the interface for end users." },
  { term:"Validation Rule (Data Validation)",
    cat:"Content & Rules",
    def:"A conditional rule on a form cell or row that turns cells red / green or enforces approval when values fail a business condition (variance > threshold, negative, etc.).",
    hint:"Drives visual alerts and can block promotion in the approval cycle." },
  { term:"Business Rule",
    cat:"Content & Rules",
    def:"A scripted Essbase calculation that allocates, aggregates, or derives data. Built in Calculation Manager with prompts, variables, and template support.",
    hint:"Two languages: Calc Script (classic) and Groovy (modern, data-aware)." },
  { term:"Groovy Rule",
    cat:"Content & Rules",
    def:"A Java-based scripting rule type that can inspect the edited form cells, call REST APIs, loop, and run targeted calcs — far more flexible than Calc Script.",
    hint:"Data-aware: only operates on changed cells → big performance win." },
  { term:"Ruleset",
    cat:"Content & Rules",
    def:"An ordered collection of business rules that execute sequentially, optionally sharing prompts so the user enters them only once for the whole set.",
    hint:"Merge prompts flag consolidates identical runtime prompts." },

  /* ---------------- Reports (1) ---------------- */
  { term:"Reports (Narrative Reporting)",
    cat:"Content & Rules",
    def:"The modern cloud reporting tool for Planning that replaces Financial Reporting. Supports pixel-perfect books, bursting, and embedded grids from Planning or other EPM sources.",
    hint:"Replaces classic 'Financial Reports'; bursting sends per-entity PDFs." },

  /* ---------------- Modules (8) ---------------- */
  { term:"Financials Module",
    cat:"Modules",
    def:"A pre-built Planning framework for income statement, balance sheet, and cash flow planning, with templates for direct or indirect method and driver-based revenue/expense planning.",
    hint:"Enable at creation; configure features granularly (Revenue, Expense, BS, CF)." },
  { term:"Workforce Module",
    cat:"Modules",
    def:"A pre-built module for headcount, salary, compensation, and benefits planning. Supports employee-only, job-only, or combined employee+job planning.",
    hint:"Assumptions drive benefits/taxes/merit; you can update many employees at once." },
  { term:"Capital Module",
    cat:"Modules",
    def:"A pre-built module for planning capital assets — tangible assets, intangibles, and leases — including depreciation/amortization, transfers, retirements, and funding.",
    hint:"Tracks asset lifecycle and feeds balance sheet and cash flow in Financials." },
  { term:"Projects Module",
    cat:"Modules",
    def:"A pre-built module for contract, indirect, and capital projects planning — revenue, expense, milestones, resources, and rollup to the enterprise plan.",
    hint:"Supports Contract, Capital, and Indirect project types." },
  { term:"Strategic Modeling",
    cat:"Modules",
    def:"A long-range financial modeling module (separate from the Planning cube) for what-if scenarios, M&A analysis, and multi-year forecasts. Built on the Strategic Model engine.",
    hint:"Not an Essbase cube; uses its own model structure and simulation engine." },
  { term:"Module Integration",
    cat:"Modules",
    def:"Pre-configured data pushes between modules (e.g., Workforce salary → Financials P&L, Capital depreciation → Financials) so changes in one module flow automatically.",
    hint:"Set up via configurable integrations on each module's configure card." },
  { term:"Configure Task",
    cat:"Modules",
    def:"The per-module card in the Application > Configure page where administrators enable features, set defaults, import mappings, and drive dimension configuration.",
    hint:"One Configure card per enabled module; run in a recommended order." },
  { term:"Best Practice — Enable Only What You Need",
    cat:"Modules",
    def:"Oracle's guidance to enable module features incrementally so unused artifacts and dimensions don't bloat the app or confuse users; features can be added later.",
    hint:"Disabled features can still be enabled later — start minimal." },

  /* ---------------- Operations (3) ---------------- */
  { term:"EPM Automate",
    cat:"Operations",
    def:"A command-line utility for scripting EPM Cloud administration — backups, data/metadata loads, rules, user provisioning, and daily maintenance window tasks.",
    hint:"Used for scheduled jobs, CI/CD, and migrations between pods." },
  { term:"Daily Maintenance Window",
    cat:"Operations",
    def:"A nightly service-initiated window in which Oracle backs up the service and applies patches. Admins can shift the start time; it's required and cannot be skipped.",
    hint:"You pick the start hour; backups live in the Inbox/Outbox for 60 days." },
  { term:"Intelligent Performance Management (IPM)",
    cat:"Operations",
    def:"An EPM Cloud feature set combining Predictive Planning, IPM Insights, and auto-predict that surfaces anomalies and forecasts using built-in ML on Planning data.",
    hint:"ML-driven: detects bias, variance patterns, and suggests forecast values." },
  { term:"Approval Unit",
    cat:"Operations",
    def:"The basic object in the approval process — typically an intersection of Entity, Scenario, and Version (and sometimes a user-defined dim) that flows through a review cycle.",
    hint:"Hierarchy + Scenario + Version = one approval unit path." },
  { term:"Approval Unit Hierarchy",
    cat:"Operations",
    def:"The approval path defined over a primary dimension (usually Entity) that determines which users own, review, and approve each node, with optional bottom-up or distribute start.",
    hint:"Two start modes: Bottom-up (promote) and Distribute (delegate down)." },

  /* ---------------- Application Setup — expansion (10) ---------------- */
  { term:"BSO (Block Storage Option)",
    cat:"Application Setup",
    def:"An Essbase cube type used as the Input cube in Planning. Planners enter data here, and business rules / calc scripts execute against it.",
    hint:"Write-back + rule execution happens in BSO, not ASO." },
  { term:"ASO (Aggregate Storage Option)",
    cat:"Application Setup",
    def:"An Essbase cube type used as the Reporting cube. Built for huge volumes and fast queries; does not run calc scripts and planners do not input here.",
    hint:"Read-heavy reporting; no business rules; used for bursting and large reports." },
  { term:"Essbase",
    cat:"Application Setup",
    def:"The multi-dimensional OLAP database engine underlying Planning. Both BSO (input) and ASO (reporting) cubes are Essbase cube types.",
    hint:"Think 'the database under the hood' — Planning sits on top of Essbase." },
  { term:"Hybrid Essbase",
    cat:"Application Setup",
    def:"An Essbase mode that blends BSO and ASO behavior — BSO block structure with on-the-fly aggregation like ASO. Default for EPM Standard / Enterprise and required for 13-period calendars and Budget Revisions.",
    hint:"Required for: 13-period calendars and Budget Revisions." },
  { term:"Module Artifact Prefix",
    cat:"Application Setup",
    def:"The two-or-three-letter prefix on predefined artifact names that identifies the owning module. Custom artifact names are NOT allowed to use these prefixes.",
    hint:"OEP_ = common · OFS_ = Financials · OWP_ = Workforce · OPF_ = Projects · OCX_ = Capital." },
  { term:"Refresh Database",
    cat:"Application Setup",
    def:"The action that pushes outline changes (added/removed members, renamed dims, updated properties) from the Planning metadata into the Essbase cube. Must be run after any metadata change.",
    hint:"Actions menu → Refresh Database. Forgetting this is a classic 'why is my member missing' bug." },
  { term:"User Variable",
    cat:"Application Setup",
    def:"A per-planner saved selection for a dimension (e.g., their Entity, Scenario, Version, Years, Reporting Currency) set in Tools → User Preferences. Forms reference user variables to auto-scope the POV.",
    hint:"Every planner must set these before entering data — otherwise forms are empty or broken." },
  { term:"Getting Started Checklist",
    cat:"Application Setup",
    def:"The exam-tested ordered sequence for standing up a Planning Modules app: create app → add currencies → review integrations → enable features → configure + run rules → refresh DB → set user variables → import data → provision users → set rule security → design reports → publish to planners → define approvals → map data between modules.",
    hint:"Order matters — enable features is locked once done; refresh DB comes after every metadata change." },
  { term:"Enable Features",
    cat:"Application Setup",
    def:"The per-module step where the Service Administrator turns on specific module capabilities (e.g., Workforce granularity, Financials revenue/expense/BS/CF). Puts the app into maintenance mode and, once enabled, features can only be added, not removed.",
    hint:"Start minimal — you can add later, but you can't turn features off." },
  { term:"Alias Table",
    cat:"Application Setup",
    def:"A Planning mechanism for giving each dimension member alternate display names (e.g., per language). Up to 32 total; one is used internally, leaving 31 usable.",
    hint:"32 max · 1 internal · 31 usable." },

  /* ---------------- Content & Rules — expansion (4) ---------------- */
  { term:"Smart Push",
    cat:"Content & Rules",
    def:"A Data Map triggered by saving a form — pushes the affected slice to a target cube automatically. Same mechanism as Data Map, different activation.",
    hint:"'Data Map + form save = Smart Push.' Fastest way to keep a target cube in sync while users plan." },
  { term:"Calculation Manager",
    cat:"Content & Rules",
    def:"The graphical authoring tool for business rules, rulesets, templates, and Groovy rules. Lets admins build flow-chart style calculations with components, prompts, variables, and error handling.",
    hint:"Home → Rules → Create/Edit opens Calculation Manager." },
  { term:"Calc Script (Classic Rule)",
    cat:"Content & Rules",
    def:"The traditional Essbase scripting language used for business rules — declarative FIX/ENDFIX blocks, formulas, and calc functions. Runs across every cell in its FIX scope, not just edited cells.",
    hint:"Calc Script recalculates every cell in scope — use Groovy when you only want edited cells." },
  { term:"Substitution Variable",
    cat:"Content & Rules",
    def:"A named placeholder (e.g., &CurrMonth, &CurrYear) maintained at the application level and referenced inside forms, rules, and jobs. Lets you move 'the current period' forward in one place without editing every artifact.",
    hint:"Update once → every artifact using it shifts. Common for rolling forecasts." },

  /* ---------------- Modules — expansion (13) ---------------- */
  { term:"Workforce Granularity",
    cat:"Modules",
    def:"The level at which Workforce plans compensation. Pick exactly one when first enabling the module: Employee only, Job only, or Employee + Job. Choice is locked after first enable.",
    hint:"Employee+Job = per-employee comp with job linkage. Pick before your first Enable Features." },
  { term:"Benefits and Taxes Wizard",
    cat:"Modules",
    def:"The Workforce wizard that configures each Component through Details → Rates → Review screens. Prerequisite: you MUST import members into the Component dimension (and configure Options and Tiers) on the Configure page before launching.",
    hint:"Import Component members FIRST — this prerequisite is on every exam." },
  { term:"Component Dimension (Workforce)",
    cat:"Modules",
    def:"The Workforce dimension that holds individual Additional Earnings, Benefits, and Taxes members. Max 30 members total across these three categories.",
    hint:"Import members here before launching the Benefits and Taxes Wizard." },
  { term:"Merit-Based Planning",
    cat:"Modules",
    def:"A Workforce option that applies a merit-rate increase to salary. Requires Employee or Employee + Job granularity. Assumptions set Global or Per-Entity; include Merit Month, Cut-off Date, and a Default Merit Rate for new hires.",
    hint:"Run Process Loaded Data after updating merit assumptions to sync at employee level." },
  { term:"Flexible Account Mapping",
    cat:"Modules",
    def:"A Workforce feature that lets you map Salary and Merit to any Financials account (not just OFS_Salaries). Mapping can be Global or per-Entity; drivers are Grade or Defaults.",
    hint:"Enable when a client wants Workforce comp to land in their own chart of accounts." },
  { term:"Split-Funded FTE",
    cat:"Modules",
    def:"A Workforce feature that splits an FTE's cost across multiple sparse dimensions (cost center, entity, project). Requires Employee or Employee+Job granularity and a Master FTE Value entered on Employee Master Data form (stored in OEP_Home Entity).",
    hint:"If Master FTE changes, run Synchronize Definition to recalculate." },
  { term:"Project Types",
    cat:"Modules",
    def:"The three project categories in the Projects module: Contract (external, revenue-bearing), Indirect (internal, no revenue), and Capital (projects that produce a capitalized asset).",
    hint:"Contract · Indirect · Capital. Project Benefits only apply to Indirect and Capital." },
  { term:"Resource Classes",
    cat:"Modules",
    def:"The three revenue/expense assumption types in Projects: Labor (FTEs, hours, rates — can pull from Workforce), Equipment (units, rates — can pull from Capital), and Material (unit costs × quantity).",
    hint:"Labor · Equipment · Material. NOT overhead, funding, or milestones." },
  { term:"Project Benefits",
    cat:"Modules",
    def:"Projects feature (Indirect and Capital only) for tracking financial benefits ($), non-financial benefits (CSAT, user growth), and qualitative benefits used to justify the project.",
    hint:"Not available on Contract projects — those are already revenue-bearing." },
  { term:"Project Management Cloud Integration",
    cat:"Modules",
    def:"Bidirectional integration between EPM Planning Projects and Oracle Project Management (ERP). Supports Indirect and Capital projects only. Requires Hybrid Essbase; uses a 12-period calendar (monthly, 4-4-5, 5-4-4, or 4-5-4 — NOT 4-4-4) and MM/DD/YY date format. Only actual costs transfer; budget validation by total amount only.",
    hint:"Indirect + Capital only. Three jobs: Export Projects & Budgets · Import Project Actuals · Import Projects & Budgets (one-time)." },
  { term:"Custom Depreciation Methods",
    cat:"Modules",
    def:"Capital module capability to define depreciation or amortization methods beyond the built-in straight-line, declining balance, etc. Configured post-enable on the Capital Configure page.",
    hint:"Built-in methods cover most cases; use Custom for non-standard schedules." },
  { term:"Budget Revisions",
    cat:"Modules",
    def:"A specialized Financials feature that integrates with Oracle ERP Cloud Budgetary Control. Requires Hybrid Essbase, single currency, and your own chart of accounts. Adds Scenario OEP_Adopted Budget (and optional OEP_Consumed). Max 30 active revisions.",
    hint:"Control Budget Source Type in ERP Cloud must be 'EPM Financials module' — NOT 'Hyperion Planning'." },
  { term:"Chart of Accounts Choice (Financials)",
    cat:"Modules",
    def:"When enabling Financials, the admin picks between using Oracle's provided chart of accounts (enables driver-based planning + full predefined dashboards) or 'Use your own COA' (direct + trend planning; to reuse provided dashboards, add accounts as shared members under OFS_Total Revenue / Cost of Sales / OpEx / Cash).",
    hint:"Provided COA = fastest path; Own COA = more work but matches your real GL." },

  /* ---------------- Operations — expansion (8) ---------------- */
  { term:"Predictive Planning",
    cat:"Operations",
    def:"An IPM component that fits time-series forecast models (ETS, ARIMA, seasonal variants) to historical Planning data and writes predicted values to a target scenario/version. Available with EPM Enterprise.",
    hint:"Pick historical range → model auto-selected → predictions written to a target Scenario/Version." },
  { term:"AutoPredict",
    cat:"Operations",
    def:"IPM feature that schedules Predictive Planning jobs so forecasts auto-refresh when historical data loads. Available with EPM Enterprise AND with Planning in EPM Standard — the one IPM feature in Standard.",
    hint:"Only IPM feature included in EPM Standard. Everything else in IPM needs Enterprise." },
  { term:"IPM Insights",
    cat:"Operations",
    def:"An IPM component that scans Planning data for anomalies, forecast bias, and variance patterns, then surfaces them as cards for admins and planners to review.",
    hint:"ML-driven anomaly detection over Planning data — shows up in the Insights panel." },
  { term:"Bring Your Own ML (PMML Import)",
    cat:"Operations",
    def:"An IPM workflow where a data scientist trains a model externally (scikit-learn, R, Oracle Data Science) and exports it as a PMML file. An EPM admin imports the PMML, maps its input fields to Planning dimensions, and deploys it — Planning auto-generates the Groovy rules to call it.",
    hint:"Data scientist exports a .pmml → admin imports → maps inputs → deploy. PMML file must exist BEFORE the admin imports." },
  { term:"Permission Priority (Deny > None > Write > Read)",
    cat:"Operations",
    def:"The rule for evaluating conflicting access across groups, inheritance, and artifacts: Deny always wins, then None, then Write, then Read. The classic exam trap is 'Write + None = None'.",
    hint:"Closest member overrides parent; Deny always wins; None beats Write." },
  { term:"Clone Snapshot",
    cat:"Operations",
    def:"A service-admin feature that produces an exact copy of an application in a target environment — it exports the source snapshot, deletes the target's current app and data, and imports the snapshot in one end-to-end run.",
    hint:"Different from Migration Export (artifacts only) and Migration Backup (recovery file only)." },
  { term:"Scheduled Job",
    cat:"Operations",
    def:"A job configured under Home → Application → Jobs. Job types include Refresh Database, Clear Cube, Run Business Rule / Ruleset, Import / Export Data / Metadata, Run Data Rule, Smart Push, Data Map. Supports substitution variables and daily/weekly/monthly/on-demand schedules.",
    hint:"Get email on completion. Running jobs can't be deleted until they finish." },
  { term:"EPM Automate Top Commands",
    cat:"Operations",
    def:"The CLI commands most tested on the exam: runBusinessRule, importMetadata, importData / exportData, runDataRule, uploadFile / downloadFile, runDailyMaintenance, downloadSnapshot, login / logout.",
    hint:"Nightly backup pattern: login → runDailyMaintenance → downloadSnapshot → logout." },
];

const ESSAYS = [
  { q:"A client wants to plan revenue, OpEx, capex, and headcount in one application. How would you choose between a Planning app with Modules and a FreeForm app, and what trade-offs matter?",
    hint:"Modules: fastest implementation, pre-built artifacts, standard integrations — but you adopt Oracle's schema.\nFreeForm: total flexibility over dims/cubes — but you build everything from scratch.\nChoose modules for standard processes; FreeForm for niche or highly-custom models.\nHybrid possible: enable some modules + add user-defined dims + Custom module for unique processes." },
  { q:"Explain valid intersections vs cell-level security. When would you use one over the other, and how do they interact with form and member access?",
    hint:"Valid intersections: business-logic filtering (what combinations make sense).\nCell-level security: permission-based filtering (who can see/edit a cell).\nUse valid intersections first to simplify the data model; layer cell security for sensitive intersections (HR comp).\nOrder: member access → artifact access → valid intersections → cell security. Deny wins." },
  { q:"Compare Data Maps and Data Integrations. Which is better for cross-application data movement and why?",
    hint:"Data Map: fast push within same EPM Cloud environment, limited transformation, supports Smart Push.\nData Integration: richer transformations, cross-source imports (ERP Cloud, file, etc.), drill-through, mapping rules, scheduling.\nChoose Data Map for intra-app cube pushes, Data Integration for external sources or complex transforms." },
  { q:"A planner complains their business rule is slow on a form with thousands of cells. How does Groovy change this, and what other optimizations should you consider?",
    hint:"Groovy is data-aware: reads only the edited cells (getEditedCells), so calc scope is tiny.\nOther levers: Fix() narrowing, FIXPARALLEL, dense/sparse tuning, aggregation strategy, ASO vs BSO, Smart Push filters.\nGroovy also lets you short-circuit if no relevant edits occurred." },
  { q:"How would you design a navigation flow for three roles (executive, cost-center planner, HR analyst)?",
    hint:"One flow per role (or group-scoped flows).\nExecutive: dashboards + reports + KPI card; hide rules and detailed forms.\nCost-center planner: forecast/actual forms + workforce inputs + approvals card.\nHR analyst: workforce forms + employee lifecycle + compensation reports.\nUse clusters for topic grouping; tabs for sub-areas; artifact hides for clarity." },
  { q:"Walk through the steps to enable Workforce for a client planning headcount and compensation for 2,000 employees across 40 entities.",
    hint:"1. Create Planning app (or enable Workforce module on existing one).\n2. Choose granularity: employee, job, or employee+job.\n3. Configure currency, performance settings, and custom dimensions.\n4. Import employees and jobs via Data Integration or bulk load templates.\n5. Set compensation assumptions (merit, taxes, benefits, FTE rules).\n6. Build Workforce-specific forms and dashboards; load beginning headcount.\n7. Connect to Financials via module integration to push comp expense to P&L." },
  { q:"What is Intelligent Performance Management, and how would you set up a forecast model for monthly revenue?",
    hint:"IPM = Predictive Planning + IPM Insights + auto-predict + ML models.\nSteps: prepare historical data (enough periods), choose member scope, set seasonality, let ML pick a model (ARIMA, ETS) or train a custom one, deploy to a Scenario/Version, review bias/variance, publish to a target form.\nMonitor IPM Insights for anomalies after each actuals load." },
  { q:"Describe the Planning approval process end-to-end. What's the difference between bottom-up and distribute starts?",
    hint:"1. Define approval unit hierarchy on Entity (primary dim) + Scenario + Version.\n2. Assign owners/reviewers/validators per node.\n3. Attach data validations to enforce thresholds.\n4. Start the process: Bottom-up = leaf owners Promote upward; Distribute = top owner pushes budgets down, then leaves return them.\n5. States flow: Not Started → Under Review → Approved / Rejected.\n6. Use Process Status dashboard and notifications; audit via approval history." },
  { q:"A client wants to automate nightly Planning backups and a monthly refresh from ERP Cloud. What tools and pattern would you use?",
    hint:"Backups: EPM Automate scripts (login → runDailyMaintenance → downloadSnapshot → logout) on a scheduler (Windows Task/cron).\nERP refresh: Data Integration job connected to ERP Cloud, scheduled, with mapping rules and drill-through. Can be triggered via EPM Automate too.\nConsider error notifications, retry logic, and a rotating snapshot archive off-pod." },
  { q:"A report author needs to produce 200 per-entity P&L PDFs each month. Which reporting tool would you use and how do you design it?",
    hint:"Use Reports (Narrative Reporting engine) with bursting.\nDesign: one pixel-perfect report with Entity as the bursting dimension, populated from a Planning grid.\nBursting definition: iterate over Entity members, one PDF per member, delivered via email or saved to a library folder.\nFallback: scheduled job + EPM Automate for distribution." },
  { q:"Walk through the full Getting Started checklist for a new Planning Modules app. Which steps are order-sensitive and which can slide?",
    hint:"Order-sensitive: (1) Create app → (2) Add currencies → (3) Review integrations → (4) Enable features (locks after) → (5) Configure + run rules → (6) Refresh database → (7) Set user variables.\nThen flexible-but-sequenced: (8) Import data → (9) Provision users → (10) Rule security → (11) Reports → (12) Publish to planners → (13) Approvals → (14) Data maps between modules.\nRefresh database must run after every metadata change." },
  { q:"What are the five layers of Planning security, and how does Deny > None > Write > Read play out when a user is in two groups?",
    hint:"Layers: 1) Role (SA > Power User > User > Viewer) 2) Artifact permissions (can they open it?) 3) Member access (R/W/None/Deny) 4) Valid intersections 5) Cell-level security.\nEvaluation: Deny always wins. None beats Write. Closest member overrides parent.\nClassic trap: Group A = Write, Group B = None → user gets None. To unblock, remove the None, don't add more Writes." },
  { q:"A client is enabling Workforce for the first time. What decisions are locked at Enable, and in what order do you make them?",
    hint:"Locked at first enable: Granularity (Employee / Job / Employee + Job), Employee Demographics (must be selected at first enable if wanted), 53-Week Planning, granularity mapping dimensions.\nOrder: pick granularity → pick demographics → choose comp components → enable Merit / FTE / Flex Account Mapping → Configure page: import Components, set Options/Tiers → run Benefits and Taxes Wizard.\nRemind the client: you can add features later, but cannot remove them." },
  { q:"Describe the Benefits and Taxes Wizard prerequisites and the three screens it walks through.",
    hint:"Prerequisites (on the Configure page) BEFORE launching the wizard: import members into the Component dimension, configure Options (Benefits / Additional Earnings), configure Tiers (Taxes).\nWizard screens: Details (type, value type, max value, taxable, threshold scope) → Rates (rate tables, tiers) → Review.\nComponent Types: Simple, Rate Table, Rate Table and Threshold, Custom." },
  { q:"A client wants to link Workforce with Projects so project plans reflect real employees and rates. What integration design do you recommend?",
    hint:"Enable Workforce BEFORE Projects so employees and jobs exist when Projects turns on.\nUse Data Maps / Smart Push: Compensation Data → feeds labor cost; Headcount/FTE → feeds utilization.\nAlign Resource Classes: Labor in Projects pulls hours + rates from Workforce jobs.\nRun Project Integration data maps on schedule; drill-through from Projects back to Workforce for audit." },
];

/* ---------------------------------------------------------
   ESSAY_MC — one multiple-choice question per essay prompt.
   Used for Learn "essay concepts" mode and Hard quiz difficulty.
   --------------------------------------------------------- */
const ESSAY_MC = [
  { topic:"Planning vs FreeForm",
    q:"A client has a highly custom revenue-allocation process that doesn't fit the Financials module. Which application approach gives the most flexibility while still using Planning features?",
    opts:["Modules-only Planning application","FreeForm Planning application with user-defined dimensions","Strategic Modeling only","Essbase standalone cube"],
    correct:1,
    explain:"FreeForm keeps all Planning capabilities (forms, rules, reports, IPM) but lets you design your own cubes and dimensions without adopting module schemas." },
  { topic:"Valid intersections vs cell security",
    q:"Which statement best distinguishes valid intersections from cell-level security?",
    opts:["Both are permission-based","Valid intersections restrict data model combinations; cell security restricts user access to specific cells","Valid intersections only apply to ASO cubes","Cell security always overrides valid intersections"],
    correct:1,
    explain:"Valid intersections enforce business-logical combinations for everyone; cell-level security adds user- or group-based restrictions on top." },
  { topic:"Data Map vs Data Integration",
    q:"Which scenario is the best fit for a Data Map rather than a Data Integration?",
    opts:["Importing a CSV from a third-party ERP nightly","Pushing data between two Plan Types inside the same Planning application on form save","Mapping COA accounts from Oracle Fusion into Planning","Running a multi-step transformation with drill-through"],
    correct:1,
    explain:"Data Maps (with Smart Push) are optimized for intra-app cube-to-cube movement on save. External/complex transformations belong to Data Integration." },
  { topic:"Groovy performance",
    q:"Why does Groovy typically outperform Calc Script business rules on form-save calculations?",
    opts:["Groovy always skips aggregation","Groovy rules are data-aware and can scope calcs to only the edited cells","Groovy bypasses Essbase entirely","Calc Scripts can't read dimensions"],
    correct:1,
    explain:"Groovy's getEditedCells / grid context APIs let the rule narrow its FIX to what the user actually changed, shrinking the block count processed." },
  { topic:"Navigation flows",
    q:"A company wants different user experiences for executives, planners, and HR. The recommended approach is:",
    opts:["Build one global flow and let roles hide themselves","Create role- or group-scoped navigation flows and hide irrelevant artifacts per flow","Disable modules for each role","Use EPM Automate at login"],
    correct:1,
    explain:"Role- or group-scoped navigation flows with tailored clusters/tabs are the standard way to customize the UX per audience." },
  { topic:"Workforce granularity",
    q:"A client wants to plan headcount and compensation at the individual employee level, tracking specific jobs per person. The correct Workforce configuration is:",
    opts:["Employee-only","Job-only","Employee and Job","Strategic Modeling"],
    correct:2,
    explain:"Employee + Job granularity supports per-employee comp with job linkage; the other modes drop one side of that detail." },
  { topic:"IPM",
    q:"Which component of IPM uses historical data to automatically generate baseline forecasts?",
    opts:["Valid intersections","Predictive Planning / auto-predict","Data validations","Approval units"],
    correct:1,
    explain:"Predictive Planning and auto-predict train ML models (ETS, ARIMA, etc.) on history to produce baseline forecasts pushed to a target scenario." },
  { topic:"Approval starts",
    q:"Which statement correctly describes the difference between Bottom-up and Distribute approval starts?",
    opts:["Bottom-up starts at the top and pushes budgets down; Distribute pulls from leaves","Distribute starts at the top owner, pushes targets down, leaves return them; Bottom-up starts at leaves and promotes upward","Both behave identically","Only Bottom-up supports reviewers"],
    correct:1,
    explain:"Bottom-up = leaves promote upward. Distribute = top owner distributes targets to leaves, which then submit back up." },
  { topic:"Backups / EPM Automate",
    q:"The most reliable way to pull a nightly Planning snapshot to an on-prem archive is:",
    opts:["Manually download from the UI","A scheduled EPM Automate script that runs login → downloadSnapshot → logout","A Data Map","A Groovy rule"],
    correct:1,
    explain:"EPM Automate is the supported scripting tool for automated backups, refreshes, and other cloud admin actions; it's scheduled externally (cron/Task Scheduler)." },
  { topic:"Reports bursting",
    q:"To produce 200 per-entity PDFs from a single Planning report monthly, you would use:",
    opts:["Dashboard 2.0","Reports bursting with Entity as the bursting dimension","A composite form","Strategic Modeling"],
    correct:1,
    explain:"Reports (Narrative Reporting) bursting iterates the designated dimension and outputs one artifact per member, delivered on schedule." },
  { topic:"Required dimensions",
    q:"Which of these is NOT a required dimension in a Planning Modules application?",
    opts:["Account","Period","Product","Scenario"],
    correct:2,
    explain:"The six required dimensions are Account, Period, Years, Scenario, Version, and Entity (+ Currency when multicurrency is on). Product is user-defined — common, but not required." },
  { topic:"BSO vs ASO",
    q:"A planner needs to enter budget values and have business rules calculate against them. Which cube type is this?",
    opts:["ASO (Aggregate Storage)","BSO (Block Storage) — the Input cube","Hybrid Essbase only","Reporting cube"],
    correct:1,
    explain:"Input happens in the BSO cube and rules run against BSO. ASO is for high-volume reporting and does not run calc scripts." },
  { topic:"Refresh Database",
    q:"You added a new Entity member to the Planning outline. What must you do before planners see it on forms?",
    opts:["Run Smart Push","Run Refresh Database (Actions menu)","Restart the service","Nothing — it's automatic"],
    correct:1,
    explain:"Metadata changes don't reach the Essbase cube until Refresh Database runs. This is the classic 'member is missing' fix." },
  { topic:"Permission evaluation",
    q:"A user is in Group A (Write on Entity E1) and Group B (None on Entity E1). What access does the user have?",
    opts:["Write","Read","None","Deny"],
    correct:2,
    explain:"Deny > None > Write > Read. None overrides Write — the user is blocked on E1 until the None is removed." },
  { topic:"Budget Revisions prerequisites",
    q:"A client wants to use Budget Revisions with ERP Cloud Budgetary Control. Which set of prerequisites is correct?",
    opts:["Single currency, provided COA, standard Essbase","Hybrid Essbase, single currency, own chart of accounts","Multicurrency, Hybrid Essbase, own COA","Hybrid Essbase, multicurrency, provided COA"],
    correct:1,
    explain:"Budget Revisions requires Hybrid Essbase, single currency, and the client's own chart of accounts. Multicurrency is not supported." },
  { topic:"Predictive Planning scope",
    q:"A customer is on EPM Standard (not Enterprise). Which IPM feature can they still use?",
    opts:["IPM Insights","Bring Your Own ML","AutoPredict","Predictive Planning manual mode"],
    correct:2,
    explain:"AutoPredict is the one IPM feature available with Planning in EPM Standard. Everything else in IPM (Insights, PMML import, full Predictive Planning) requires EPM Enterprise." },
  { topic:"Smart Push vs Data Map",
    q:"Which best describes Smart Push?",
    opts:["A separate tool that replaces Data Maps","A Data Map that runs automatically when a form is saved","An ERP Cloud integration","A reporting-only feature"],
    correct:1,
    explain:"Smart Push uses the same underlying Data Map; the difference is activation — it fires on form save so the target cube stays in sync during planning." },
  { topic:"Component Dimension (Workforce)",
    q:"Before launching the Benefits and Taxes Wizard, what must an admin do?",
    opts:["Run Refresh Database only","Import members into the Component dimension and configure Options/Tiers","Enable 53-Week Planning","Disable Flexible Account Mapping"],
    correct:1,
    explain:"The wizard operates on Component members — you must import them and configure Options (Benefits / Additional Earnings) and Tiers (Taxes) on the Configure page first." },
  { topic:"Module enablement order",
    q:"A client plans to use both Workforce and Projects, with Projects tracking employee utilization. In what order should they be enabled?",
    opts:["Projects first, then Workforce","Either order works","Workforce first, then Projects","Only enable Workforce — Projects is optional"],
    correct:2,
    explain:"Workforce holds employee details (salary, hours, FTE) that Projects consumes for utilization. Enable Workforce first so the data is there when Projects integrations run." },
];

/* ---------------------------------------------------------
   EXAM_Q — real-format exam practice questions from ExamsIndex
   1Z0-1080-25 demo PDF. Includes single-select AND multi-select
   (pick 2 / pick 3) questions. `correct` is always an array of
   zero-based option indices. `pick` is the required selection count.
   --------------------------------------------------------- */
const EXAM_Q = [
  {
    topic: "IPM — Bring Your Own ML",
    pick: 1,
    q: "Which task must be completed before EPM administrators import a Machine Learning model into Planning?",
    opts: [
      "Data Scientists build and train the ML model in a data science tool and save it as a PMML file.",
      "Data Scientists create Groovy rules designed to evaluate historical data and identify patterns.",
      "EPM Administrators create a data model and push data to it to generate a PMML file.",
      "EPM Administrators create data maps and Groovy rules to move and process data.",
    ],
    correct: [0],
    explain: "The 'Bring Your Own ML' feature requires data scientists to build and train the ML model in a third-party data science tool (or Oracle Data Science Cloud) and save it as a PMML file. The EPM administrator imports that prebuilt PMML file into Planning; the app then auto-generates the Groovy rules needed to integrate the model.",
  },
  {
    topic: "Operations — Scheduling Jobs",
    pick: 2,
    q: "You need to schedule a weekly data import job. Which two statements are true about scheduling jobs?",
    opts: [
      "You can check the execution status of a job only if it completed.",
      "You can set the daily maintenance time when scheduling cloning environment jobs.",
      "You can set to receive notifications when the job has completed.",
      "You can schedule an Import Data job to run later at intervals.",
      "You can delete jobs that are currently processing.",
    ],
    correct: [2, 3],
    explain: "C and D are true. The Jobs console supports email notifications on completion (C) and recurring schedules for Import Data jobs — daily, weekly, or at a custom interval (D). A is false: the Jobs console shows Running status in real time. B is false: daily maintenance time is a system-wide application setting, not a per-job option. E is false: running jobs can't be deleted until they complete or fail.",
  },
  {
    topic: "Navigation Flows — Customization Categories",
    pick: 3,
    q: "Which three are Navigation Flow customization categories?",
    opts: [
      "Role",
      "User",
      "Group",
      "Artifact",
      "Global",
    ],
    correct: [0, 2, 4],
    explain: "Navigation flows are customized at three levels: Role (e.g., Planner vs Administrator), Group (teams or departments), and Global (the default applied to all users unless overridden). User-level customization isn't supported — flows target roles/groups. 'Artifact' is a migration concept, not a nav-flow category.",
  },
  {
    topic: "Projects — Revenue & Expense Assumptions",
    pick: 3,
    q: "Which three types of revenue and expense assumptions drive data calculations in Projects?",
    opts: [
      "Working days and hours",
      "Plan start year",
      "Standard rates",
      "Program mappings",
      "Project rates",
      "Discount rates",
    ],
    correct: [0, 2, 4],
    explain: "Working days & hours (resource availability → labor cost and revenue), Standard rates (default hourly/daily rates across projects), and Project rates (project-specific rates that override the standard) all directly drive Projects financials. Plan start year is a timeline parameter, Program mappings integrate data across programs, and Discount rates are for NPV/financial analysis — none are direct revenue/expense drivers.",
  },
  {
    topic: "Module Integration — Workforce → Projects",
    pick: 1,
    q: "Which module should you enable first to track the utilization of employees in Projects?",
    opts: [
      "Projects module before Financials module",
      "Financials module before Projects module",
      "Workforce module before Projects module",
      "Projects module before Workforce module",
    ],
    correct: [2],
    explain: "Workforce holds employee details (roles, salaries, hours, FTE) that Projects consumes to calculate utilization. Enable Workforce first, then Projects can pull the employee data via integration/data maps and track utilization against project tasks and budgets. Financials handles P&L but doesn't manage employee-level data.",
  },
  {
    topic: "Module Integration — Workforce → Financials",
    pick: 1,
    q: "You can override expense lines in Financials with the more detailed values that Workforce stores. What steps would you take to move the detailed values to Financials?",
    opts: [
      "In data maps, for Financial Statement Integration, define how the detailed Workforce accounts roll up into the Financials accounts.",
      "On the Financials Integration Summary form, calculate compensation data to update the underlying details for Workforce data.",
      "On the Financials Integration Summary form, from the Actions menu, select the Rollup business rule.",
      "In data maps, for Compensation Data, synchronize and then push the data.",
    ],
    correct: [0],
    explain: "The out-of-the-box 'Financial Statement Integration' data map defines how detailed Workforce accounts (salary, taxes, benefits) roll up into Financials accounts. Once the mapping is set, you synchronize and push the data. The Financials Integration Summary form only views rolled-up data — there's no 'Rollup' rule in its Actions menu, and the Compensation Data map alone is too narrow for this scenario.",
  },
  {
    topic: "Financials — Revenue & Expense Navigation Flow",
    pick: 1,
    q: "You want to input data into Financials. For Financials, there is a predefined navigation flow with cards listed for both Revenue and Expenses. What is the sequence of the cards for Revenue and Expenses?",
    opts: [
      "Overview, Driver and Trend Based, Rolling Forecast, Direct Entry, Income Statement",
      "Assumptions, Allocations, Detailed Bottom Up, Strategic Top-Down, Direct Input, Overview",
      "Assumptions, Direct Input, Driver and/or Trend Based, High Level Overview, Detailed Overview, Summary",
      "Overview, Assumptions, Allocations, Detailed Bottom-Up, Driver and/or Trend based, Direct Input",
    ],
    correct: [0],
    explain: "The out-of-the-box Financials navigation flow walks users from high-level context into detailed entry and back to reporting: Overview → Driver and Trend Based → Rolling Forecast → Direct Entry → Income Statement. 'Allocations', 'Detailed Bottom-Up', and 'Strategic Top-Down' appear in other flows/modules but are not part of the default Financials Revenue & Expenses sequence.",
  },
  {
    topic: "Operations — Clone Snapshot",
    pick: 1,
    q: "What feature can Service Administrators use to automatically complete all the actions required to create an exact copy of the current application in a target environment — including the removal of the current application and data, if any, from the target environment?",
    opts: [
      "Replicate Snapshot",
      "Migration Export",
      "Clone Snapshot",
      "Migration Backup",
    ],
    correct: [2],
    explain: "Clone Snapshot (on the source environment) automates the entire end-to-end clone: export a snapshot, delete the target's existing application and data, then import and apply the snapshot so the target is an exact copy of the source. Migration Export only exports artifacts, Migration Backup just creates a recovery file, and 'Replicate Snapshot' isn't a real feature name.",
  },
  {
    topic: "Required Dimensions",
    pick: 3,
    q: "Which three of the following are required dimensions in every Planning Modules application (excluding Currency, which is added only when Multicurrency is enabled)?",
    opts: [
      "Account",
      "Product",
      "Scenario",
      "Entity",
      "Region",
      "Department",
    ],
    correct: [0, 2, 3],
    explain: "The required dims are Account, Period, Years, Scenario, Version, and Entity (+ Currency when multicurrency is on). Product, Region, and Department are typical user-defined dimensions but are not required.",
  },
  {
    topic: "Workforce Granularity",
    pick: 3,
    q: "Which three granularity levels are available when first enabling the Workforce module?",
    opts: [
      "Employee",
      "Job",
      "Department",
      "Employee and Job",
      "Position",
    ],
    correct: [0, 1, 3],
    explain: "Workforce granularity is one of Employee, Job, or Employee and Job. This choice is locked on first enable. Department and Position aren't granularity options — they're dimensions.",
  },
  {
    topic: "Project Types",
    pick: 3,
    q: "Which three are valid Project Types in the Projects module?",
    opts: [
      "Contract",
      "Indirect",
      "Grants",
      "Capital",
      "Research",
    ],
    correct: [0, 1, 3],
    explain: "The three project types are Contract, Indirect, and Capital. Grants and Research aren't project types in the Projects module.",
  },
  {
    topic: "Permission Hierarchy",
    pick: 1,
    q: "A user belongs to Group A with Write on an Entity and Group B with None on the same Entity. What is their effective access?",
    opts: [
      "Write (unions take the most permissive)",
      "Read (fallback)",
      "None (None overrides Write)",
      "Deny",
    ],
    correct: [2],
    explain: "The evaluation order is Deny > None > Write > Read. None always overrides Write — this is the single most tested permission trap on the exam.",
  },
  {
    topic: "Budget Revisions Prerequisites",
    pick: 3,
    q: "Budget Revisions integrates with Oracle ERP Cloud Budgetary Control. Which three configurations are required?",
    opts: [
      "Hybrid Essbase",
      "Multicurrency enabled",
      "Single currency",
      "Your own chart of accounts (not provided COA)",
      "ASO-only reporting",
    ],
    correct: [0, 2, 3],
    explain: "Budget Revisions needs Hybrid Essbase, single currency, and your own chart of accounts. Multicurrency is NOT supported, and reporting is not constrained to ASO-only.",
  },
  {
    topic: "PMML / Bring Your Own ML",
    pick: 1,
    q: "An EPM admin wants to deploy a custom machine learning model into Planning via IPM. What file format does the data scientist provide?",
    opts: [
      "A Groovy script file (.grv)",
      "A PMML file (.pmml)",
      "A .cube export",
      "A CSV with model coefficients",
    ],
    correct: [1],
    explain: "Bring Your Own ML is driven by PMML — a universal XML-based ML exchange format. The data scientist trains externally (e.g., scikit-learn → sklearn2pmml), exports .pmml, and the admin imports it into IPM where Planning auto-wires the Groovy.",
  },
  {
    topic: "Module Prefixes",
    pick: 2,
    q: "Which two of these predefined prefixes identify Workforce and Projects artifacts, respectively?",
    opts: [
      "OEP_",
      "OWP_",
      "OFS_",
      "OPF_",
      "OCX_",
    ],
    correct: [1, 3],
    explain: "OWP_ prefixes Workforce artifacts; OPF_ prefixes Projects artifacts. OEP_ is common-across-modules, OFS_ is Financials, OCX_ is Capital. Custom artifact names may NOT use these prefixes.",
  },
  {
    topic: "Calendar / PM Cloud Integration",
    pick: 1,
    q: "A client wants to integrate Projects with Oracle Project Management (ERP). Which accounting calendar is NOT supported for this integration?",
    opts: [
      "12-period monthly",
      "4-4-5",
      "5-4-4",
      "4-4-4",
    ],
    correct: [3],
    explain: "Project Management Cloud integration supports 12-period monthly, 4-4-5, 5-4-4, and 4-5-4. 4-4-4 (36-week pseudo-calendars) is not supported.",
  },
  {
    topic: "Things Locked After Creation",
    pick: 3,
    q: "Which three of the following CANNOT be changed after a Planning Modules app is created?",
    opts: [
      "Input cube name",
      "Reporting cube name",
      "A new user-defined dimension member",
      "13-period vs 12-month calendar choice",
      "The set of planners who have Write access",
    ],
    correct: [0, 1, 3],
    explain: "Cube names and the calendar shape (13-period vs 12-month) are locked at creation. You can always add members to user-defined dimensions and change user access after go-live.",
  },
  {
    topic: "EPM Automate Backup Pattern",
    pick: 1,
    q: "Which sequence of EPM Automate commands is the standard nightly-snapshot-to-archive pattern?",
    opts: [
      "login → runDailyMaintenance → downloadSnapshot → logout",
      "login → importMetadata → exportData → logout",
      "downloadSnapshot → login → logout",
      "runBusinessRule → downloadSnapshot → logout",
    ],
    correct: [0],
    explain: "The supported nightly pattern is login → runDailyMaintenance (lets backup complete) → downloadSnapshot (pull it local) → logout. Scheduled externally via cron or Task Scheduler.",
  },
  {
    topic: "Groovy Use Cases",
    pick: 3,
    q: "Which three are scenarios where Groovy is required or strongly recommended over Calc Script?",
    opts: [
      "You need to calculate only the cells the user just edited on a form",
      "You need to call a REST API from inside the rule",
      "You need a simple FIX/ENDFIX aggregation across a dimension",
      "You're adding a new employee, project, or asset (Add Requisition / Add Project / Add Asset)",
      "You want the rule to run every time the daily maintenance window fires",
    ],
    correct: [0, 1, 3],
    explain: "Groovy shines for: edited-cells-only calcs (performance), REST calls, loops/conditional logic, and Add-X templates. A plain FIX aggregation is fine in Calc Script; daily-maintenance-triggered runs are scheduled jobs, not a rule-language concern.",
  },
  {
    topic: "IPM Components",
    pick: 2,
    q: "Which two of the following are components of Intelligent Performance Management (IPM)?",
    opts: [
      "IPM Insights",
      "Predictive Planning",
      "Strategic Modeling",
      "Narrative Reporting",
    ],
    correct: [0, 1],
    explain: "IPM = Predictive Planning + IPM Insights + AutoPredict + Bring Your Own ML. Strategic Modeling and Narrative Reporting are separate products/features, not part of IPM.",
  },
];
