/* =========================================================
   1Z0-1080-25 — Oracle Planning 2025 Implementation Professional
   CARDS (30) · ESSAYS (10) · ESSAY_MC (10)
   Categories:
     "Application Setup"   — Planning overview, dims, metadata/data, security
     "Content & Rules"     — Forms/dashboards/navflows, rules, reports
     "Modules"             — Financials, Workforce, Capital, Projects, Strategic Modeling
     "Operations"          — Maintenance, IPM, Approvals
   ========================================================= */

const CARDS = [
  /* ---------------- Application Setup (8) ---------------- */
  { term:"Planning Application",
    cat:"Application Setup",
    def:"An Oracle Cloud EPM application built on Essbase cubes that supports budgeting, forecasting, and what-if analysis across standard business processes or Custom modules.",
    hint:"Created from Planning or FreeForm; stored in EPM Cloud." },
  { term:"FreeForm Application",
    cat:"Application Setup",
    def:"A flexible Planning application type that lets you define your own cubes and dimensions without enabling the pre-built modules (Financials, Workforce, etc.).",
    hint:"Pick this when you don't want the module content; you design dims yourself." },
  { term:"Required Dimension",
    cat:"Application Setup",
    def:"A dimension that every Planning application must contain: Account, Period, Year, Scenario, Version, and Entity (plus Currency when multicurrency is enabled).",
    hint:"Six required dims; Currency is added automatically when multicurrency is on." },
  { term:"User-Defined Dimension",
    cat:"Application Setup",
    def:"A custom dimension you add to model business-specific analysis (Product, Market, Department, etc.). Up to the Essbase cube's dimension limits.",
    hint:"Added after required dims; drives custom analysis in BSO/ASO cubes." },
  { term:"Dimension Hierarchy",
    cat:"Application Setup",
    def:"The parent-child tree structure of a dimension that controls aggregation. Base members hold data; upper-level members roll up via consolidation operators (+, -, ~, ^).",
    hint:"Tilde (~) = don't consolidate; caret (^) = never consolidate." },
  { term:"Valid Intersection",
    cat:"Application Setup",
    def:"A rule that restricts which cell combinations across dimensions can accept or display data, enforcing that only meaningful intersections are visible.",
    hint:"Example: Capex accounts only valid for Capital entities." },
  { term:"Cell-Level Security",
    cat:"Application Setup",
    def:"Security applied at specific dimension intersections to hide or restrict data, in addition to artifact-level access, using member combinations.",
    hint:"Finer-grained than Read/Write on a form — targets cells, not artifacts." },
  { term:"Data Map",
    cat:"Application Setup",
    def:"An EPM Cloud feature that pushes data from one cube or application to another by mapping source and target dimensions, including smart pushes from forms.",
    hint:"Used to move data between Plan Types or apps; supports Smart Push on save." },
  { term:"Data Integration",
    cat:"Application Setup",
    def:"The EPM Cloud tool (formerly Data Management) that imports/exports data with mapping rules, dimension mapping, drill-through, and scheduled jobs.",
    hint:"Replaces legacy Data Management; supports file, direct, and connected integrations." },

  /* ---------------- Application Setup cont. — Security (2) ---------------- */
  { term:"Security Provisioning",
    cat:"Application Setup",
    def:"Assigning predefined roles (Service Administrator, Power User, User, Viewer) to users or groups at the application level to control what features they can use.",
    hint:"Roles are hierarchical: Service Administrator > Power User > User > Viewer." },
  { term:"Access Permissions",
    cat:"Application Setup",
    def:"Read / Write / None / Deny permissions assigned to members, forms, rules, and other artifacts, granted to users or groups and evaluated with None overriding Write.",
    hint:"Union of group rights, but Deny (None) always wins over Write." },

  /* ---------------- Content & Rules (8) ---------------- */
  { term:"Data Form",
    cat:"Content & Rules",
    def:"A grid-based input and analysis surface where planners enter, view, and analyze data. Point-of-view and page dimensions define context; rows/columns show members.",
    hint:"Simple forms = single layout; composite forms embed multiple forms together." },
  { term:"Composite Form",
    cat:"Content & Rules",
    def:"A form that combines multiple simple forms into one layout so users can see and update related data side-by-side with shared POVs where applicable.",
    hint:"Useful for master-detail entry; saves navigation between forms." },
  { term:"Dashboard",
    cat:"Content & Rules",
    def:"A visual layout that combines charts, grids, forms, and commentary to summarize planning data. Supports drill-down, interactive filters, and global POVs.",
    hint:"Dashboard 2.0 is the modern engine with richer charts and layout control." },
  { term:"Navigation Flow",
    cat:"Content & Rules",
    def:"A configurable UI path with cluster cards, tabs, and sub-tabs that customizes the user experience per role or group, hiding artifacts not relevant to them.",
    hint:"Role-scoped flows simplify the interface for end users." },
  { term:"Validation Rule (Data Validation)",
    cat:"Content & Rules",
    def:"A conditional rule on a form cell or row that turns cells red / green or enforces approval when values fail a business condition (variance > threshold, negative, etc.).",
    hint:"Drives visual alerts and can block promotion in the approval cycle." },
  { term:"Business Rule",
    cat:"Content & Rules",
    def:"A scripted Essbase calculation that allocates, aggregates, or derives data. Built in Calculation Manager with prompts, variables, and template support.",
    hint:"Two languages: Calc Script (classic) and Groovy (modern, data-aware)." },
  { term:"Groovy Rule",
    cat:"Content & Rules",
    def:"A Java-based scripting rule type that can inspect the edited form cells, call REST APIs, loop, and run targeted calcs — far more flexible than Calc Script.",
    hint:"Data-aware: only operates on changed cells → big performance win." },
  { term:"Ruleset",
    cat:"Content & Rules",
    def:"An ordered collection of business rules that execute sequentially, optionally sharing prompts so the user enters them only once for the whole set.",
    hint:"Merge prompts flag consolidates identical runtime prompts." },

  /* ---------------- Reports (1) ---------------- */
  { term:"Reports (Narrative Reporting)",
    cat:"Content & Rules",
    def:"The modern cloud reporting tool for Planning that replaces Financial Reporting. Supports pixel-perfect books, bursting, and embedded grids from Planning or other EPM sources.",
    hint:"Replaces classic 'Financial Reports'; bursting sends per-entity PDFs." },

  /* ---------------- Modules (8) ---------------- */
  { term:"Financials Module",
    cat:"Modules",
    def:"A pre-built Planning framework for income statement, balance sheet, and cash flow planning, with templates for direct or indirect method and driver-based revenue/expense planning.",
    hint:"Enable at creation; configure features granularly (Revenue, Expense, BS, CF)." },
  { term:"Workforce Module",
    cat:"Modules",
    def:"A pre-built module for headcount, salary, compensation, and benefits planning. Supports employee-only, job-only, or combined employee+job planning.",
    hint:"Assumptions drive benefits/taxes/merit; you can update many employees at once." },
  { term:"Capital Module",
    cat:"Modules",
    def:"A pre-built module for planning capital assets — tangible assets, intangibles, and leases — including depreciation/amortization, transfers, retirements, and funding.",
    hint:"Tracks asset lifecycle and feeds balance sheet and cash flow in Financials." },
  { term:"Projects Module",
    cat:"Modules",
    def:"A pre-built module for contract, indirect, and capital projects planning — revenue, expense, milestones, resources, and rollup to the enterprise plan.",
    hint:"Supports Contract, Capital, and Indirect project types." },
  { term:"Strategic Modeling",
    cat:"Modules",
    def:"A long-range financial modeling module (separate from the Planning cube) for what-if scenarios, M&A analysis, and multi-year forecasts. Built on the Strategic Model engine.",
    hint:"Not an Essbase cube; uses its own model structure and simulation engine." },
  { term:"Module Integration",
    cat:"Modules",
    def:"Pre-configured data pushes between modules (e.g., Workforce salary → Financials P&L, Capital depreciation → Financials) so changes in one module flow automatically.",
    hint:"Set up via configurable integrations on each module's configure card." },
  { term:"Configure Task",
    cat:"Modules",
    def:"The per-module card in the Application > Configure page where administrators enable features, set defaults, import mappings, and drive dimension configuration.",
    hint:"One Configure card per enabled module; run in a recommended order." },
  { term:"Best Practice — Enable Only What You Need",
    cat:"Modules",
    def:"Oracle's guidance to enable module features incrementally so unused artifacts and dimensions don't bloat the app or confuse users; features can be added later.",
    hint:"Disabled features can still be enabled later — start minimal." },

  /* ---------------- Operations (3) ---------------- */
  { term:"EPM Automate",
    cat:"Operations",
    def:"A command-line utility for scripting EPM Cloud administration — backups, data/metadata loads, rules, user provisioning, and daily maintenance window tasks.",
    hint:"Used for scheduled jobs, CI/CD, and migrations between pods." },
  { term:"Daily Maintenance Window",
    cat:"Operations",
    def:"A nightly service-initiated window in which Oracle backs up the service and applies patches. Admins can shift the start time; it's required and cannot be skipped.",
    hint:"You pick the start hour; backups live in the Inbox/Outbox for 60 days." },
  { term:"Intelligent Performance Management (IPM)",
    cat:"Operations",
    def:"An EPM Cloud feature set combining Predictive Planning, IPM Insights, and auto-predict that surfaces anomalies and forecasts using built-in ML on Planning data.",
    hint:"ML-driven: detects bias, variance patterns, and suggests forecast values." },
  { term:"Approval Unit",
    cat:"Operations",
    def:"The basic object in the approval process — typically an intersection of Entity, Scenario, and Version (and sometimes a user-defined dim) that flows through a review cycle.",
    hint:"Hierarchy + Scenario + Version = one approval unit path." },
  { term:"Approval Unit Hierarchy",
    cat:"Operations",
    def:"The approval path defined over a primary dimension (usually Entity) that determines which users own, review, and approve each node, with optional bottom-up or distribute start.",
    hint:"Two start modes: Bottom-up (promote) and Distribute (delegate down)." },
];

const ESSAYS = [
  { q:"A client wants to plan revenue, OpEx, capex, and headcount in one application. How would you choose between a Planning app with Modules and a FreeForm app, and what trade-offs matter?",
    hint:"Modules: fastest implementation, pre-built artifacts, standard integrations — but you adopt Oracle's schema.\nFreeForm: total flexibility over dims/cubes — but you build everything from scratch.\nChoose modules for standard processes; FreeForm for niche or highly-custom models.\nHybrid possible: enable some modules + add user-defined dims + Custom module for unique processes." },
  { q:"Explain valid intersections vs cell-level security. When would you use one over the other, and how do they interact with form and member access?",
    hint:"Valid intersections: business-logic filtering (what combinations make sense).\nCell-level security: permission-based filtering (who can see/edit a cell).\nUse valid intersections first to simplify the data model; layer cell security for sensitive intersections (HR comp).\nOrder: member access → artifact access → valid intersections → cell security. Deny wins." },
  { q:"Compare Data Maps and Data Integrations. Which is better for cross-application data movement and why?",
    hint:"Data Map: fast push within same EPM Cloud environment, limited transformation, supports Smart Push.\nData Integration: richer transformations, cross-source imports (ERP Cloud, file, etc.), drill-through, mapping rules, scheduling.\nChoose Data Map for intra-app cube pushes, Data Integration for external sources or complex transforms." },
  { q:"A planner complains their business rule is slow on a form with thousands of cells. How does Groovy change this, and what other optimizations should you consider?",
    hint:"Groovy is data-aware: reads only the edited cells (getEditedCells), so calc scope is tiny.\nOther levers: Fix() narrowing, FIXPARALLEL, dense/sparse tuning, aggregation strategy, ASO vs BSO, Smart Push filters.\nGroovy also lets you short-circuit if no relevant edits occurred." },
  { q:"How would you design a navigation flow for three roles (executive, cost-center planner, HR analyst)?",
    hint:"One flow per role (or group-scoped flows).\nExecutive: dashboards + reports + KPI card; hide rules and detailed forms.\nCost-center planner: forecast/actual forms + workforce inputs + approvals card.\nHR analyst: workforce forms + employee lifecycle + compensation reports.\nUse clusters for topic grouping; tabs for sub-areas; artifact hides for clarity." },
  { q:"Walk through the steps to enable Workforce for a client planning headcount and compensation for 2,000 employees across 40 entities.",
    hint:"1. Create Planning app (or enable Workforce module on existing one).\n2. Choose granularity: employee, job, or employee+job.\n3. Configure currency, performance settings, and custom dimensions.\n4. Import employees and jobs via Data Integration or bulk load templates.\n5. Set compensation assumptions (merit, taxes, benefits, FTE rules).\n6. Build Workforce-specific forms and dashboards; load beginning headcount.\n7. Connect to Financials via module integration to push comp expense to P&L." },
  { q:"What is Intelligent Performance Management, and how would you set up a forecast model for monthly revenue?",
    hint:"IPM = Predictive Planning + IPM Insights + auto-predict + ML models.\nSteps: prepare historical data (enough periods), choose member scope, set seasonality, let ML pick a model (ARIMA, ETS) or train a custom one, deploy to a Scenario/Version, review bias/variance, publish to a target form.\nMonitor IPM Insights for anomalies after each actuals load." },
  { q:"Describe the Planning approval process end-to-end. What's the difference between bottom-up and distribute starts?",
    hint:"1. Define approval unit hierarchy on Entity (primary dim) + Scenario + Version.\n2. Assign owners/reviewers/validators per node.\n3. Attach data validations to enforce thresholds.\n4. Start the process: Bottom-up = leaf owners Promote upward; Distribute = top owner pushes budgets down, then leaves return them.\n5. States flow: Not Started → Under Review → Approved / Rejected.\n6. Use Process Status dashboard and notifications; audit via approval history." },
  { q:"A client wants to automate nightly Planning backups and a monthly refresh from ERP Cloud. What tools and pattern would you use?",
    hint:"Backups: EPM Automate scripts (login → runDailyMaintenance → downloadSnapshot → logout) on a scheduler (Windows Task/cron).\nERP refresh: Data Integration job connected to ERP Cloud, scheduled, with mapping rules and drill-through. Can be triggered via EPM Automate too.\nConsider error notifications, retry logic, and a rotating snapshot archive off-pod." },
  { q:"A report author needs to produce 200 per-entity P&L PDFs each month. Which reporting tool would you use and how do you design it?",
    hint:"Use Reports (Narrative Reporting engine) with bursting.\nDesign: one pixel-perfect report with Entity as the bursting dimension, populated from a Planning grid.\nBursting definition: iterate over Entity members, one PDF per member, delivered via email or saved to a library folder.\nFallback: scheduled job + EPM Automate for distribution." },
];

/* ---------------------------------------------------------
   ESSAY_MC — one multiple-choice question per essay prompt.
   Used for Learn "essay concepts" mode and Hard quiz difficulty.
   --------------------------------------------------------- */
const ESSAY_MC = [
  { topic:"Planning vs FreeForm",
    q:"A client has a highly custom revenue-allocation process that doesn't fit the Financials module. Which application approach gives the most flexibility while still using Planning features?",
    opts:["Modules-only Planning application","FreeForm Planning application with user-defined dimensions","Strategic Modeling only","Essbase standalone cube"],
    correct:1,
    explain:"FreeForm keeps all Planning capabilities (forms, rules, reports, IPM) but lets you design your own cubes and dimensions without adopting module schemas." },
  { topic:"Valid intersections vs cell security",
    q:"Which statement best distinguishes valid intersections from cell-level security?",
    opts:["Both are permission-based","Valid intersections restrict data model combinations; cell security restricts user access to specific cells","Valid intersections only apply to ASO cubes","Cell security always overrides valid intersections"],
    correct:1,
    explain:"Valid intersections enforce business-logical combinations for everyone; cell-level security adds user- or group-based restrictions on top." },
  { topic:"Data Map vs Data Integration",
    q:"Which scenario is the best fit for a Data Map rather than a Data Integration?",
    opts:["Importing a CSV from a third-party ERP nightly","Pushing data between two Plan Types inside the same Planning application on form save","Mapping COA accounts from Oracle Fusion into Planning","Running a multi-step transformation with drill-through"],
    correct:1,
    explain:"Data Maps (with Smart Push) are optimized for intra-app cube-to-cube movement on save. External/complex transformations belong to Data Integration." },
  { topic:"Groovy performance",
    q:"Why does Groovy typically outperform Calc Script business rules on form-save calculations?",
    opts:["Groovy always skips aggregation","Groovy rules are data-aware and can scope calcs to only the edited cells","Groovy bypasses Essbase entirely","Calc Scripts can't read dimensions"],
    correct:1,
    explain:"Groovy's getEditedCells / grid context APIs let the rule narrow its FIX to what the user actually changed, shrinking the block count processed." },
  { topic:"Navigation flows",
    q:"A company wants different user experiences for executives, planners, and HR. The recommended approach is:",
    opts:["Build one global flow and let roles hide themselves","Create role- or group-scoped navigation flows and hide irrelevant artifacts per flow","Disable modules for each role","Use EPM Automate at login"],
    correct:1,
    explain:"Role- or group-scoped navigation flows with tailored clusters/tabs are the standard way to customize the UX per audience." },
  { topic:"Workforce granularity",
    q:"A client wants to plan headcount and compensation at the individual employee level, tracking specific jobs per person. The correct Workforce configuration is:",
    opts:["Employee-only","Job-only","Employee and Job","Strategic Modeling"],
    correct:2,
    explain:"Employee + Job granularity supports per-employee comp with job linkage; the other modes drop one side of that detail." },
  { topic:"IPM",
    q:"Which component of IPM uses historical data to automatically generate baseline forecasts?",
    opts:["Valid intersections","Predictive Planning / auto-predict","Data validations","Approval units"],
    correct:1,
    explain:"Predictive Planning and auto-predict train ML models (ETS, ARIMA, etc.) on history to produce baseline forecasts pushed to a target scenario." },
  { topic:"Approval starts",
    q:"Which statement correctly describes the difference between Bottom-up and Distribute approval starts?",
    opts:["Bottom-up starts at the top and pushes budgets down; Distribute pulls from leaves","Distribute starts at the top owner, pushes targets down, leaves return them; Bottom-up starts at leaves and promotes upward","Both behave identically","Only Bottom-up supports reviewers"],
    correct:1,
    explain:"Bottom-up = leaves promote upward. Distribute = top owner distributes targets to leaves, which then submit back up." },
  { topic:"Backups / EPM Automate",
    q:"The most reliable way to pull a nightly Planning snapshot to an on-prem archive is:",
    opts:["Manually download from the UI","A scheduled EPM Automate script that runs login → downloadSnapshot → logout","A Data Map","A Groovy rule"],
    correct:1,
    explain:"EPM Automate is the supported scripting tool for automated backups, refreshes, and other cloud admin actions; it's scheduled externally (cron/Task Scheduler)." },
  { topic:"Reports bursting",
    q:"To produce 200 per-entity PDFs from a single Planning report monthly, you would use:",
    opts:["Dashboard 2.0","Reports bursting with Entity as the bursting dimension","A composite form","Strategic Modeling"],
    correct:1,
    explain:"Reports (Narrative Reporting) bursting iterates the designated dimension and outputs one artifact per member, delivered on schedule." },
];
